//
// Created by Usuario on 13/05/2024.
//

#ifndef LAB_9_10_FINAL_FINAL_TESTSDYNAMICVECTOR_H
#define LAB_9_10_FINAL_FINAL_TESTSDYNAMICVECTOR_H
void myTestsDynamicVector();
#endif //LAB_9_10_FINAL_FINAL_TESTSDYNAMICVECTOR_H
